### ISSUE TITLE
API request to delete cached export fails with 403 Forbidden

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#115]

**Comment by rkorytkowski** [comment]
The request is documented at https://github.com/OpenConceptLab/oclapi/wiki/Export-API#delete-an-export-file

**Comment by davetrig** [comment]
@paynejd, can you verify that the user you are using has 'is_staff = true' in the auth_user table?
The first check in the export delete method is a check for this flag.  See below:

```
   def delete(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return HttpResponseForbidden()
        version = self.get_object()
        if version.has_export():
            key = version.get_export_key()
            if key:
                key.delete()
                return HttpResponse(status=200)

        return HttpResponse(status=204) 
```

**Comment by paynejd** [comment]
@davetrig Thanks for getting to the bottom of this. I am not using a
"staff" user, and the documentation (which I pasted below) states that you
only need administrative access to a repository. I'll switch to a staff
user for the time being, which addresses the immediate issue, but that
would also give the "datim-admin" administrative access to everything in
OCL, which is not a great idea! Is there a similarly simple method to
determine if a user has administrative access to the repository for the
export they are trying to delete?



   - Deletes a specific export file

DELETE /[:ownerType/]:owner/:repoType/:repo/:repoVersion/export/


   - Notes
      - If HEAD version is requested, the API will return 405 Not Allowed.
      - The passed authorization token must have administrative access to
      the repository in order to delete the export file

**Comment by davetrig** [comment]
@paynejd Would 'is_superuser' do the trick?  How else is administrative access determined?  Nothing else is jumping out at me at the moment.

**Comment by paynejd** [comment]
Staff and superuser are basically the same. "administrative rights" for
resources are determined by resource ownership and organization membership.

Basically, if a user owns the object (e.g.
/users/JohnDoe/sources/DoeSource/), then only that user has admin rights to
it. If an org owns the object (e.g. /orgs/PEPFAR/sources/MER/), then each
member of that organization has admin rights to it. (Yes, it's a simplistic
permissions schema!) There should be some methods to check permissions, but
I do not know what they are.

You could take a look at the permissions checking for some other actions --
i.e. editing a concept, creating a new source, etc.

Hopefully this provides a little direction?

**Comment by davetrig** [comment]
Yup, I'm on it.  

Should I also assume that a user with either is_staff or is_superuser should be allowed to perform the action, regardless of administrative access to the resource?

**Comment by paynejd** [comment]
Yes, that is correct!

**Comment by davetrig** [comment]
Modified API to allow repository admin (as it is described above) to perform export delete.
Pull request submitted

**Comment by paynejd** [comment]
Will test after this is deployed...

**Comment by davetrig** [comment]
I closed and recreated the pull request for this issue.  The code got conflated with changes for issue 119, and I subsequently screwed up a merge when catching up from upstream.

**Comment by rkorytkowski** [comment]
Merged! I'll test once deployed to qa.

**Comment by rkorytkowski** [comment]
It seems we are missing some S3 privileges, since it now fails with:
api_1     | ERROR 2017/10/16 09:59:19 [base.py:210 handle_uncaught_exception()] Internal Server Error: /orgs/PEPFAR/collections/MER-R-Facility-FY16Q1Q2Q3/v2017-10-13T100044.037131/export/
api_1     | Traceback (most recent call last):
api_1     |   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
api_1     |     response = callback(request, *callback_args, **callback_kwargs)
api_1     |   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
api_1     |     return self.dispatch(request, *args, **kwargs)
api_1     |   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
api_1     |     return view_func(*args, **kwargs)
api_1     |   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 327, in dispatch
api_1     |     response = self.handle_exception(exc)
api_1     |   File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 324, in dispatch
api_1     |     response = handler(request, *args, **kwargs)
api_1     |   File "/code/collection/views.py", line 575, in delete
api_1     |     key.delete()
api_1     |   File "/usr/local/lib/python2.7/site-packages/boto/s3/key.py", line 546, in delete
api_1     |     headers=headers)
api_1     |   File "/usr/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 760, in delete_key
api_1     |     query_args_l=None)
api_1     |   File "/usr/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 779, in _delete_key_internal
api_1     |     response.reason, body)
api_1     | S3ResponseError: S3ResponseError: 403 Forbidden
api_1     | <?xml version="1.0" encoding="UTF-8"?>
api_1     | <Error><Code>AccessDenied</Code><Message>Access Denied</Message>

**Comment by rkorytkowski** [comment]
I'll follow up with OpenMRS infra team to have it fixed...

**Comment by rkorytkowski** [comment]
Fixed!
