### ISSUE TITLE
Migrate required SqlViews from dev to production DATIM servers

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#38]
We want to start running API requests directly against the DATIM Global server that are in the format that we need. We now have accounts for the dev server and can test existing SqlViews or create our own. Need to identify existing views or create views for each of the requests the mediator is going to perform.

**Comment by maurya** [comment]
Hi @paynejd, 

Summary on DHIS2 endpoints. I hope it answers this ticket -

Indicators and Mechanisms are available to the public with API calls.
Facilities/Org Units are behind authentication of Datim Global DHIS2 account with API calls.

Each API call is basically an SQLView that requires a dataset token in the request to respond. We can specify the format (CSV, JSON, HTML) in the request.

Next Steps/questions: 

- Can we get all the indicators/mechanism datasets with one call instead of one call for each indicator/mechanism dataset?
- How are new datasets entered into the DHIS2 system? is there something in that process that will affect our workflow?

**Comment by paynejd** [comment]
Maurya, thanks for this. Will the DATIM team need to create new SQLViews
then customized for the requests that we want? Also, will we need to
authenticate?

**Comment by paynejd** [comment]
Note that this issue has been repurposed...

**Comment by maurya** [comment]
https://docs.google.com/document/d/1FHJcCdZoto52drw4WKLsDvpsnEMU6up8lrOUHAU2Ppk/edit#
