### ISSUE TITLE
Deploy oclapi to Jetstream

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/DATIM-Metadata-Project#56]
OpenMRS Jetstream, under Cintia's leadership, is using Terraform. This task involves walking through the steps to add oclapi to OpenMRS' Terraform plan.

@rkorytkowski,
* You can find documentation on the [ITSM wiki](https://github.com/openmrs/openmrs-contrib-itsmresources/wiki)'s and [ITSM Terraform repo](https://github.com/openmrs/openmrs-contrib-itsm-terraform) (access restricted, but available to `/dev/5`s) and coordinate with Cintia. This will likely be the first addition to Terraform not performed by Cintia herself, so please use & update the ITSM wiki documentation to fill in any gaps or lessons learned to reduce the burden on Cintia when the next person needs to add to Terraform.
* oclapi should be deployed to a medium server (16 GB RAM)
* The corresponding ITSM ticket for this activity is [ITSM-4018](https://issues.openmrs.org/browse/ITSM-4018)

**Comment by bmamlin** [comment]
Jetstream is designed for processing power, not storage, so the server comes with 60 GB. If we will need more than 40 GB of disk space up front or in the near future, then we will need to set up a separate volume. If large amounts of storage are needed (e.g., 100s of GB), then we may need to look elsewhere for storage (e.g., Amazon S3).

@paynejd, how much storage space is required for oclapi (near term & long term)?

**Comment by paynejd** [comment]
I would expect that 40GB would be sufficient, however I've pasted the
results of df -h on openconceptlab.org here. There are approximately
200,000 resources on this server (between CIEL and Ethiopia), so I'm not
clear as to why /dev/vda1 is using 119GB. Rafal, since you have access to
production, do you want to look around to see what is taking up all that
space and if that's avoidable? It may just be log files or other temp
files. Burke, I can also give you access to the server if you send me your
public key.

[image: image.png]

**Comment by rkorytkowski** [comment]
It's mongo backups that take 76 GB on openconceptlab.org. One backup takes ~300 MB and they seem to be taken every day. We should be fine keeping 14 of them or so.

Next ocl logs take 36 GB. There are 4999 ocl_web log files at the moment. There are a few new created each day. We do not have to keep more than for the last 14 days. 

We should be fine with 40 GB of space.

**Comment by bmamlin** [comment]
I'd recommend using a script(s) – e.g., cron job(s) – to ensure backups are compressed and thinned. In other projects, I took the approach like keeping daily backups for 1 week, weekly backups for 1 month, and monthly backups for a year.

For the OpenMRS infrastructure we use AWS S3 for backups and then glacier for cold storage. If this is not addressed in the terraform setup documentation, then we can ask Cintia. I'm pretty sure she sets up AWS CLI to automatically send files from a designated backup folder to S3.

**Comment by paynejd** [comment]
OCL already uses AWS S3 for caching exports of repository versions and that
could work for backups as well

**Comment by rkorytkowski** [comment]
Progress so far:
1) https://ocl.openmrs.org/ and https://ocl-stg.openmrs.org/ are ready. Awaiting for https://ocl-qa.openmrs.org/
2) Made necessary changes for jetstream docker deployment in jetstream branches (will be merged with master once we are done with migration) at
https://github.com/OpenConceptLab/oclapi/tree/jetstream
https://github.com/OpenConceptLab/ocl_web/tree/jetstream
3) Created builds at https://ci.openmrs.org/browse/OCL-OA/latest (it was easier to setup than GoCD since all credentials and scripts for jetstream are already on Bamboo)
4) OCL releases pushed to https://hub.docker.com/u/openconceptlab/dashboard/
Remaining work:
1) Add ocl_web to Bamboo
2) Allow to set OCL_API_TOKEN for oclapi instead of it being auto-generated so it can be used by ocl_web
3) Copy docker-compose files to https://github.com/openmrs/openmrs-contrib-ansible-docker-compose/tree/master/files
4) Manually move mogodb and postgres data from digitalocean to jetstream instances.
5) Setup tests on Bamboo for oclapi and ocl_web

**Comment by rkorytkowski** [comment]
Completed today:
1. Add ocl_web to Bamboo
2. Allow to set OCL_API_TOKEN for oclapi instead of it being auto-generated so it can be used by ocl_web

Remaining:
1. Copy docker-compose files to https://github.com/openmrs/openmrs-contrib-ansible-docker-compose/tree/master/files
2. Manually move mongodb and postgres data from DigitalOcean to JetStream instances.
3. Setup tests on Bamboo for oclapi and ocl_web
4. Setup redirects from openconceptlab.org

**Comment by rkorytkowski** [comment]
Completed:
1. Setup SMTP for confirmation e-mails
2. Migrated data for production and staging from DigitalOcean to JetStream
3. All envs up and running
Remaining:
1. Setup redirects from openconceptlab.org
2. Fix running UI tests

**Comment by paynejd** [comment]
@rkorytkowski I planned to wait to redirect openconceptlab.org to the new servers until mid to late September, so there's no rush on that unless it is going to change the configuration. That gives us time to get the PEPFAR content in good shape before making those servers public.

**Comment by rkorytkowski** [comment]
@paynejd okay! One thing to consider is that if we are going to keep both ocl.openmrs.org and openconceptlab.org running they will be out of sync soon. There's no easy way to move data from openconceptlab.org to ocl.openmrs.org without loosing content on ocl.openmrs.org... Are we okay with that? Are we planning to load data from openconceptlab.org to ocl.openmrs.org again before changing redirects?

Unit tests are setup at https://ci.openmrs.org/browse/OCL-OUT
